pins.digitalWritePin(DigitalPin.P0, 1)
pins.digitalWritePin(DigitalPin.P1, 1)
pins.digitalWritePin(DigitalPin.P2, 1)
basic.forever(function () {
    pins.digitalWritePin(DigitalPin.P0, 0)
    basic.pause(10000)
    pins.digitalWritePin(DigitalPin.P0, 1)
    basic.pause(100)
    pins.digitalWritePin(DigitalPin.P2, 0)
    basic.pause(10000)
    pins.digitalWritePin(DigitalPin.P2, 1)
    basic.pause(100)
    pins.digitalWritePin(DigitalPin.P1, 0)
    basic.pause(3000)
    pins.digitalWritePin(DigitalPin.P1, 1)
    basic.pause(100)
})
